---
depends_on: []
kind: pipeline
name: ci
services:
- image: docker:dind
  name: docker
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run
steps:
- commands:
  - make tools-image-build registry=reg.dist.svc.cluster.znet:5000
  - make tools-image-push registry=reg.dist.svc.cluster.znet:5000
  image: reg.dist.svc.cluster.znet:5000/zachfi/streamgo-ci-tools:latest
  name: build-tools
  pull: always
  volumes:
  - name: dockersock
    path: /var/run
  when:
    ref:
    - refs/heads/main
- commands:
  - make compile-only
  image: reg.dist.svc.cluster.znet:5000/zachfi/streamgo-ci-tools:latest
  name: compile-only
  pull: always
- commands:
  - make docker registry=reg.dist.svc.cluster.znet:5000
  - make docker-push registry=reg.dist.svc.cluster.znet:5000
  image: reg.dist.svc.cluster.znet:5000/zachfi/streamgo-ci-tools:latest
  name: build-app
  pull: always
  volumes:
  - name: dockersock
    path: /var/run
  when:
    ref:
    - refs/heads/main
trigger:
  ref:
  - refs/heads/main
  - refs/heads/dependabot/**
  - refs/pull/*/head
volumes:
- name: dockersock
  temp: {}
---
kind: signature
hmac: 27a155760873c15828f7b10e69e4e2f07443c317f925cfb205ec56f77c03a128

...
