"clone":
  "git":
    "dns":
    - "8.8.8.8"
    - "8.8.4.4"
    "image": "woodpeckerci/plugin-git"
"services":
- "image": "docker:24-dind"
  "name": "docker"
  "privileged": true
  "volumes":
  - "dockersock:/var/run"
"steps":
- "commands":
  - "sleep 60"
  "image": "alpine:3.19"
  "name": "debug-sleep-60"
  "pull": true
- "dns":
  - "8.8.8.8"
  - "8.8.4.4"
  "image": "woodpeckerci/plugin-git"
  "name": "clone"
  "pull": true
- "commands":
  - "make tools-image-build registry=reg.dist.svc.cluster.znet:5000"
  - "make tools-image-push registry=reg.dist.svc.cluster.znet:5000"
  "image": "reg.dist.svc.cluster.znet:5000/zachfi/streamgo-ci-tools:latest"
  "name": "build-tools"
  "pull": true
  "volumes":
  - "dockersock:/var/run"
  "when":
  - "branch": "main"
    "event": "push"
- "commands":
  - "sleep 600"
  "image": "alpine:3.19"
  "name": "debug-sleep"
  "pull": true
  "when":
  - "branch": "debug"
  - "event": "manual"
- "commands":
  - "make compile-only"
  "image": "reg.dist.svc.cluster.znet:5000/zachfi/streamgo-ci-tools:latest"
  "name": "compile-only"
  "pull": true
  "when":
  - "event": "push"
  - "event": "pull_request"
- "commands":
  - "make docker registry=reg.dist.svc.cluster.znet:5000"
  - "make docker-push registry=reg.dist.svc.cluster.znet:5000"
  "image": "reg.dist.svc.cluster.znet:5000/zachfi/streamgo-ci-tools:latest"
  "name": "build-app"
  "pull": true
  "volumes":
  - "dockersock:/var/run"
  "when":
  - "branch": "main"
    "event": "push"
