"services":
- "environment":
    "DOCKER_TLS_CERTDIR": ""
  "image": "docker:24-dind"
  "name": "docker"
  "privileged": true
"skip_clone": true
"steps":
- "commands":
  - "sleep 60"
  "image": "alpine:3.19"
  "name": "debug-sleep-60"
  "pull": true
  "when":
  - "event": "push"
  - "event": "pull_request"
  - "event": "manual"
- "image": "woodpeckerci/plugin-git"
  "name": "clone"
  "pull": true
  "when":
  - "event": "push"
  - "event": "pull_request"
  - "event": "manual"
- "commands":
  - "make tools-image-build registry=reg.dist.svc.cluster.znet:5000"
  - "make tools-image-push registry=reg.dist.svc.cluster.znet:5000"
  "environment":
    "DOCKER_HOST": "tcp://docker:2375"
    "DOCKER_TLS_VERIFY": "0"
  "image": "reg.dist.svc.cluster.znet:5000/zachfi/streamgo-ci-tools:latest"
  "name": "build-tools"
  "pull": true
  "when":
  - "branch": "main"
    "event": "push"
- "commands":
  - "sleep 600"
  "image": "alpine:3.19"
  "name": "debug-sleep"
  "pull": true
  "when":
  - "branch": "debug"
    "event": "push"
  - "event": "manual"
- "commands":
  - "make compile-only"
  "image": "reg.dist.svc.cluster.znet:5000/zachfi/streamgo-ci-tools:latest"
  "name": "compile-only"
  "pull": true
  "when":
  - "event": "push"
  - "event": "pull_request"
  - "event": "manual"
- "commands":
  - "make docker registry=reg.dist.svc.cluster.znet:5000"
  - "make docker-push registry=reg.dist.svc.cluster.znet:5000"
  "environment":
    "DOCKER_HOST": "tcp://docker:2375"
    "DOCKER_TLS_VERIFY": "0"
  "image": "reg.dist.svc.cluster.znet:5000/zachfi/streamgo-ci-tools:latest"
  "name": "build-app"
  "pull": true
  "when":
  - "branch": "main"
    "event": "push"
